#!/usr/bin/env bash
# pacman-statusline font installer — macOS only.
#
#   1. Ensures MesloLGS NF (4 weights) lives in ~/Library/Fonts/
#   2. Patches each weight with a horizontally-mirrored pac-man glyph
#   3. Writes the chosen codepoint to ~/.config/pacman-statusline/config
#
# Wiring the script into Claude Code is done separately via Claude Code's
# own `/statusline` slash command — point it at this repo's
# statusline-command.sh and Claude Code writes the path into settings.json.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATCHER="$REPO_DIR/scripts/patch-font.py"
FONT_DIR="$HOME/Library/Fonts"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/pacman-statusline"
CONFIG_FILE="$CONFIG_DIR/config"

WEIGHTS=("Regular" "Bold" "Italic" "Bold Italic")
MEDIA_BASE="https://github.com/romkatv/powerlevel10k-media/raw/master"

log()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31mxx\033[0m %s\n' "$*" >&2; exit 1; }

# Percent-encode spaces in a weight name for the download URL.
url_encode_weight() {
  printf '%s' "$1" | sed 's/ /%20/g'
}

# --- preflight ---------------------------------------------------------------

[[ "$(uname -s)" == "Darwin" ]] || die "this installer is macOS-only for now"
command -v uv   >/dev/null     || die "missing dependency: uv (https://docs.astral.sh/uv/)"
command -v curl >/dev/null     || die "missing dependency: curl"
[[ -f "$PATCHER" ]]             || die "patcher script not found at $PATCHER"

mkdir -p "$FONT_DIR" "$CONFIG_DIR"

# --- ensure fonts exist ------------------------------------------------------

for weight in "${WEIGHTS[@]}"; do
  file="$FONT_DIR/MesloLGS NF $weight.ttf"
  if [[ ! -f "$file" ]]; then
    log "downloading MesloLGS NF $weight"
    url="$MEDIA_BASE/MesloLGS%20NF%20$(url_encode_weight "$weight").ttf"
    curl -fL --progress-bar -o "$file" "$url" \
      || die "failed to download $url"
  fi
done

# --- patch each weight -------------------------------------------------------
#
# The first weight scans for a free PUA slot. Remaining weights are told to
# use that same codepoint — all four upstream weights share an identical cmap
# shape so the scan is deterministic across them.

patch_one() {
  local bak="$1" out="$2" target="${3-}"
  if [[ -n "$target" ]]; then
    uv run --quiet --with fonttools python3 "$PATCHER" "$bak" -o "$out" --target-codepoint "$target" | tail -n1
  else
    uv run --quiet --with fonttools python3 "$PATCHER" "$bak" -o "$out" | tail -n1
  fi
}

TARGET_CP=""
for weight in "${WEIGHTS[@]}"; do
  file="$FONT_DIR/MesloLGS NF $weight.ttf"
  bak="$file.bak"
  # Preserve the pristine upstream copy on first run so the patch is always
  # applied to a clean source (not a previously-patched file).
  if [[ ! -f "$bak" ]]; then
    cp "$file" "$bak"
  fi

  log "patching $weight"
  if [[ -z "$TARGET_CP" ]]; then
    TARGET_CP=$(patch_one "$bak" "$file")
    log "selected codepoint: $TARGET_CP"
  else
    got=$(patch_one "$bak" "$file" "$TARGET_CP")
    [[ "$got" == "$TARGET_CP" ]] \
      || die "codepoint mismatch on $weight: got $got, expected $TARGET_CP"
  fi
done

# --- write config ------------------------------------------------------------

log "writing $CONFIG_FILE"
cat > "$CONFIG_FILE" <<EOF
# pacman-statusline — generated by install.sh
# The left-facing pac-man glyph lives at this PUA codepoint in your patched
# MesloLGS NF font. Re-run install.sh to regenerate.
PAC_L_CODEPOINT=$TARGET_CP
EOF

# --- done --------------------------------------------------------------------

cat <<EOF

done.

  patched codepoint : $TARGET_CP
  config            : $CONFIG_FILE
  statusline script : $REPO_DIR/statusline-command.sh

next:
  1. restart your terminal (and any app using MesloLGS NF) so the patched
     font loads
  2. in Claude Code, run:  /statusline
     and paste the path:   $REPO_DIR/statusline-command.sh
EOF
